name: Test and Deploy DAGs

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r airflow/dev/requirements.txt

      - name: Test DAGs
        run: pytest airflow/dev/tests/dags/test_dag_integrity.py

      - name: Copy DAGs to production folder
        run: |
          mkdir -p airflow/dags && cp -Rv airflow/dev/dags/* airflow/dags/
        if: ${{ success() }}
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update DAGs
          branch: main
          commit_options: '--no-verify'

      

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: docker/airflow/Dockerfile
#          push: true
#          tags: your-dockerhub-username/your-docker-image-name:${{ github.sha }}
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#        if: ${{ success() }}
        
